# Generated by Django 2.2.5 on 2019-10-06 18:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('alt', models.CharField(blank=True, max_length=80, null=True, verbose_name='Краткое описание (alt)')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='MailsSendings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_last_sending', models.DateTimeField(null=True, verbose_name='Дата последнего отпраления')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Email подписанный на рассылку уведомлений',
                'verbose_name_plural': 'Emails подписанные на рассылку уведомлений',
            },
        ),
        migrations.CreateModel(
            name='TaskSendidng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_subject', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('mail_body', models.TextField(verbose_name='Тело письма')),
                ('is_complite', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('date_send', models.DateTimeField(null=True, verbose_name='Дата отправки')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('mail_email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.MailsSendings', verbose_name='Адрес еmail')),
            ],
            options={
                'verbose_name': 'Задача на рассылку',
                'verbose_name_plural': 'Задачи на рассылку',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текс на главной странице')),
                ('availavled', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('need_sending', models.BooleanField(default=True, verbose_name='Необходимо ли разослать подписчикам')),
                ('send_already', models.BooleanField(default=False, verbose_name='Расласть сразу (или по расписанию)')),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Images', verbose_name='Главное изображение поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
