# Generated by Django 2.2.5 on 2019-10-06 21:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='short_description',
            field=models.CharField(max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Текс на главной странице'),
            preserve_default=False,
        ),
    ]
